import os
import glob

# Generated by IA
# Caminho da pasta onde estão os arquivos que deseja renomear
caminho_pasta = "F:\Videos\Musicas_para_criancas"

# Número inicial para a sequência
numero_inicial = 2000

# Escolha de ordenação: "nome" ou "data"
ordenacao = "nome"  # Alterar para "data" se quiser ordenar por data de modificação

# Buscar arquivos na pasta
arquivos = glob.glob(os.path.join(caminho_pasta, "*"))

# Ordenando os arquivos conforme a escolha
if ordenacao == "nome":
    arquivos = sorted(arquivos)  # Ordenação alfabética
elif ordenacao == "data":
    arquivos = sorted(arquivos, key=os.path.getmtime)  # Ordenação por data de modificação

# Renomeando cada arquivo de forma decrescente
for i, caminho_antigo in enumerate(arquivos):
    # Calcula o número decrescente
    numero_decrescente = numero_inicial - i
    nome_arquivo = os.path.basename(caminho_antigo)
    novo_nome = f"{numero_decrescente}_{nome_arquivo}"
    caminho_novo = os.path.join(caminho_pasta, novo_nome)

    # Renomeia o arquivo
    os.rename(caminho_antigo, caminho_novo)
    print(f"Arquivo renomeado de {nome_arquivo} para {novo_nome}")

print("Renomeação concluída!")
